package io.edupilot.notification;

public enum NotificationType {
	MATERIAL_UPLOADED,
	NOTICE_PUBLISHED,
	JOIN_REQUEST_RECEIVED,
	JOIN_REQUEST_PROCESSED,
	EXAM_PUBLISHED,
	EXAM_DEADLINE_APPROACHING,
	EXAM_GRADED
}
